flywithme/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login as django_login
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from topspots import urls as spot_urls
from topspots import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^help/', views.help_page, name='help'),
    url(r'^$', views.home_page, name='home'),
    url(r'^user/(\d+)/', views.user_profile, name='user_profile'),
    url(r'^updatelocation/', views.update_location, name='update_location'),
    url(r'^useaddress/', views.use_address, name='use_address'),
    url(r'^spots/', include(spot_urls)),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', django_login, name='login', kwargs={
        'template_name': 'topspots/login.html',
        'redirect_field_name': 'next',
    }),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^favicon.ico$',
        RedirectView.as_view(url=staticfiles_storage.url('topspots/images/favicon.ico'), permanent=False),
        name="favicon"),
    # This is a hack so that users won't have access to django-allauth views I want to block
    url(r'^accounts/email/', views.go_home),
    url(r'^accounts/logout/', views.go_home),
    url(r'^accounts/login/', views.go_home),
    url(r'^accounts/signup/', views.go_home),
    url(r'^accounts/social/connections/', views.go_home),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^tips/', views.tips, name='tips'),
]

topspots/urls.py
from django.conf.urls import url

from topspots import views

urlpatterns = [
    url(r'details/(\d+)/$', views.spot_detail, name='spot_detail'),
    url(r'search/$', views.spot_search, name='spot_search'),
    url(r'save/$', views.save_spot, name='save_spot'),
    url(r'favorite/$', views.favorite, name='favorite'),
    url(r'(\d+)/comment/$', views.comment, name='comment'),
    url(r'details/(\d+)/comment/(\d+)/delete/$', views.delete_comment, name='delete_comment'),
    url(r'details/(\d+)/comment/(\d+)/reply/$', views.reply_comment, name='reply_comment'),
    url(r'details/(\d+)/comment/(\d+)/reply/delete/$', views.delete_reply, name='delete_reply'),
    url(r'details/(\d+)/comment/(\d+)/edit/$', views.edit_comment, name='edit_comment'),
    url(r'details/(\d+)/submitlink/$', views.submit_video_link, name='submit_video_link'),
    url(r'myspots/(.+)/$', views.my_spots, name='my_spots'),
    url(r'(\d+)/logpacks/$', views.log_packs, name='log_packs'),
]

topspots/models.py
import os

from django.contrib.auth.models import User
from django.contrib import messages
from django.db import models
from django.utils import timezone
from django.dispatch import receiver
from allauth.account.signals import user_signed_up


GMAPS_JS_API_KEY = os.environ['GMAPS_JS_API_KEY']


class NoAPIKeyError(Exception):
    pass


def get_map_url(address, maptype='roadmap', latlng=None, api_key=None):
    if not api_key:
        raise NoAPIKeyError('Please provide a Google Maps Static Maps API key')
    base_url = 'https://maps.googleapis.com/maps/api/staticmap'
    params = '?center={0}&zoom=15&size=640x300&maptype={1}&markers={0}&key={2}'
    return base_url + params.format(latlng or address, maptype, api_key)


class Spot(models.Model):

    name = models.TextField()
    score = models.IntegerField(default=0)
    url_name = models.TextField(default='')
    created = models.DateTimeField(default=timezone.now)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, default=90)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, default=90)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    @property
    def currently_featured_video(self):
        return self.featuredvideo_set.order_by('-featured_date').first()

    @property
    def map_url(self):
        return get_map_url(
            self.url_name, latlng=self.latlng, api_key=GMAPS_JS_API_KEY
        )

    @property
    def sat_map_url(self):
        return get_map_url(
            self.url_name, latlng=self.latlng,
            maptype='satellite', api_key=GMAPS_JS_API_KEY
        )

    @property
    def small_map_url(self):
        return self.map_url.replace('size=640x300', 'size=300x100')

    @property
    def small_long_map_url(self):
        return self.map_url.replace('size=640x300', 'size=640x100&scale=1')

    @property
    def short_name(self):
        return self.name.split(',')[0]

    @property
    def google_maps_places_url(self):
        _url = 'https://www.google.com/maps/place/'
        return _url + self.url_name

    @property
    def favorited_by_list(self):
        return self.siteuser_set.all()

    @property
    def latlng(self):
        return str(self.latitude) + ',' + str(self.longitude)

    def __str__(self):
        return self.name

    def favorited_by(self, user):
        return user in self.favorited_by_list

    @property
    def ordered_comments(self):
        return self.comment_set.order_by('-created')

    @property
    def total_packs_flown(self):
        total = self.packlog_set.aggregate(models.Sum('packs'))['packs__sum']
        return total or 0

    def packs_flown_by(self, user):
        return self.packlog_set.filter(user=user).aggregate(models.Sum('packs'))['packs__sum'] or 0


class FeaturedVideo(models.Model):
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE)
    html = models.TextField(default='')
    featured_date = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    text = models.TextField(default='')
    poster = models.ForeignKey(User, on_delete=models.CASCADE)
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class CommentReply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    poster = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True)


class SiteUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    member_since = models.DateTimeField(auto_now_add=True)
    favorites = models.ManyToManyField(Spot)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, default=None, null=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, default=None, null=True)
    address = models.TextField(null=True)
    use_address = models.BooleanField(default=False)

    @property
    def total_packs_logged(self):
        total = self.user.packlog_set.aggregate(models.Sum('packs'))['packs__sum']
        return total or 0


class PackLog(models.Model):
    packs = models.IntegerField()
    datetime_logged = models.DateTimeField(default=timezone.now)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE)


def create_siteuser(sender, instance, created, **kwargs):
    if created:
        SiteUser.objects.create(user=instance)


@receiver(user_signed_up)
def show_welcome_message(request, user, **kwargs):
    messages.success(request, 'User signup successful.')

models.signals.post_save.connect(create_siteuser, sender=User)

topspots/views.py
from datetime import datetime

from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib import auth
from django.utils.http import is_safe_url
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect

from topspots.models import Spot, PackLog, Comment, SiteUser,\
    get_map_url, CommentReply, GMAPS_JS_API_KEY

from topspots.forms import SignUpForm
from topspots.services import get_weather_conditions, get_nearby_airports,\
    get_lat_lng, get_city_state, get_location_from_address
from topspots.helpers import get_nearby_spots, paginate_query, geolocate,\
    urlize_spot_name


def authenticate_and_login(request, username, password):
    user = auth.authenticate(username=username, password=password)
    auth.login(request, user)


def home_page(request):
    '''Display top rated spots on home page'''
    sorting = request.GET.get('sort')
    all_spots = Spot.objects.all()
    user = request.user.siteuser if request.user.is_authenticated() else None

    if user and all((user.use_address, user.latitude, user.longitude)):
        user_lat = lat = user.latitude
        user_lng = lng = user.longitude
        geolocate_fail = False
    else:
        lat, lng, geolocate_fail = geolocate(request)

        user_lat = lat if not geolocate_fail else None
        user_lng = lng if not geolocate_fail else None

    if not sorting or sorting == 'near':

        spot_list = list(get_nearby_spots(lat, lng, within_miles=100))

        # Don't show nearby spots as default on home page if there are none
        sorting = 'near' if spot_list or sorting else 'favorites'

    if sorting == 'recent':
        spot_list = Spot.objects.order_by('-created', '-score')
    elif sorting == 'favorites':
        spot_list = Spot.objects.order_by('-score', '-created')

    page = request.GET.get('page')
    spots = paginate_query(page, spot_list, 10)
    spot_count = Spot.objects.count()
    user_count = SiteUser.objects.count()
    return render(request, 'topspots/home.html', {
        'spots': spots,
        'spot_count': spot_count,
        'sorting': sorting,
        'user_count': user_count,
        'geolocate_fail': geolocate_fail,
        'all_spots': all_spots,
        'user_lat': user_lat,
        'user_lng': user_lng,
    })


def spot_detail(request, spot_id):
    '''Display details of spot'''
    spot = Spot.objects.get(id=spot_id)
    pack_numbers = range(1, 101)
    user = request.user
    user_packs = spot.packs_flown_by(user) if user.is_authenticated() else 0
    conditions = get_weather_conditions(lat=spot.latitude, lng=spot.longitude)
    airports = get_nearby_airports(lat=spot.latitude, lng=spot.longitude)
    weather_checked_at = datetime.fromtimestamp(conditions['time'])
    return render(request, 'topspots/detail.html', {
        'spot': spot,
        'packs': pack_numbers,
        'user_packs': user_packs,
        'rain': conditions['rain'],
        'wind': conditions['wind'],
        'temp': conditions['temp'],
        'weather_checked_at': weather_checked_at,
        'airports': airports,
    })


def spot_search(request):
    spot_fullname = request.GET['search_query']
    # User has not entered a search query
    if not spot_fullname:
        return HttpResponseRedirect('/')

    latlng = request.GET.get('latlng')
    if latlng:
        spot_lat, spot_lng = [float(i) for i in latlng.split(',')]
    else:
        spot_lat, spot_lng = get_lat_lng(spot_fullname)

    if request.GET.get('searchtype') == 'nearby':
        # todo update so that user can enter miles
        miles = request.GET.get('miles') or 10

        # Find spots with miles of spot_lat and spot_lng
        nearby_spots_list = get_nearby_spots(spot_lat, spot_lng, miles)
        page = request.GET.get('page')
        nearby_spots = paginate_query(page, list(nearby_spots_list), 10)
        return render(request, 'topspots/nearbyspots.html', {
            'nearby_spots': nearby_spots,
            'nearby_spot_count': len(list(nearby_spots)),
            'miles_radius': miles,
            'ref_point': spot_fullname,
        })

    try:
        spot = Spot.objects.get(name=spot_fullname)
        return HttpResponseRedirect(reverse('spot_detail', args=(spot.id,)))
    except Spot.DoesNotExist:
        airports = get_nearby_airports(spot_lat, spot_lng)
        spot_url_name = urlize_spot_name(spot_fullname)
        static_url = get_map_url(
            spot_url_name, latlng=latlng, api_key=GMAPS_JS_API_KEY
        )
        place_url = 'https://www.google.com/maps/place/' + spot_url_name
        return render(request, 'topspots/spotsearch.html', {
            'spot_name': spot_fullname,
            'spot_url_name': spot_url_name,
            'static_url': static_url,
            'spot_lat': spot_lat,
            'spot_lng': spot_lng,
            'airports': airports,
            'place_url': place_url,
        })


def save_spot(request):
    if request.method == 'POST':
        spot_name = request.POST['spot_name']
        url_name = request.POST['spot_url_name']
        latitude = request.POST['spot_lat']
        longitude = request.POST['spot_lng']
        city, state = get_city_state(latitude, longitude)
        spot = Spot(
            name=spot_name,
            longitude=longitude,
            latitude=latitude,
            url_name=url_name,
            city=city,
            state=state,
            added_by=request.user,
        )
        spot.save()
        user = request.user

        if request.POST.get('add_fav') == 'on' and user.is_authenticated():
            user.siteuser.favorites.add(spot)
            spot.score += 1
            spot.save()
        return HttpResponseRedirect(reverse('spot_detail', args=(spot.id,)))
    return HttpResponseRedirect('/')


@login_required
def favorite(request):
    user = request.user
    spot_id = request.POST['spot_id']
    spot = Spot.objects.get(id=spot_id)
    if not spot.favorited_by(user.siteuser):
        spot.siteuser_set.add(user.siteuser)
        spot.score += 1
        spot.save()
    else:
        spot.siteuser_set.remove(user.siteuser)
        spot.score -= 1
        spot.save()
    return JsonResponse({'status': 'ok'})


def logout(request):
    if request.user.is_authenticated() and request.method == 'POST':
        auth.logout(request)
    return HttpResponseRedirect(reverse('home'))


def signup(request):
    icons = {
        'Username': 'user', 'Email address': 'envelope', 'Password': 'lock'
    }

    if request.method == 'POST':

        form = SignUpForm(request.POST)

        if form.is_valid():

            redirect_to = request.POST.get('next', '/')
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = '/'

            password = form.cleaned_data['password']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']

            User.objects.create_user(
                username=username, email=email, password=password
            )
            authenticate_and_login(request, username, password)
            messages.success(request, 'User signup successful.')
            return HttpResponseRedirect(redirect_to)
    else:
        form = SignUpForm()

    return render(request, 'topspots/signup.html', {
        'form': form, 'icons': icons, 'next': request.GET.get('next', '/')
    })


@login_required
def comment(request, spot_id):
    if request.POST.get('comment'):
        spot = Spot.objects.get(id=spot_id)
        Comment.objects.create(
            text=request.POST['comment'],
            poster=request.user,
            spot=spot,
        )
    return HttpResponseRedirect(reverse('spot_detail', args=(spot_id,)))


@login_required
def my_spots(request, username):
    user = User.objects.get(username=username)
    favorites = user.siteuser.favorites.order_by('-score')
    return render(request, 'topspots/myspots.html', {'favorites': favorites})


@login_required
def log_packs(request, spot_id):
    packs = request.POST['pack-select']
    spot = Spot.objects.get(id=spot_id)
    PackLog.objects.create(user=request.user, spot=spot, packs=packs)
    return HttpResponseRedirect(reverse('spot_detail', args=(spot_id,)))


@login_required
def delete_comment(request, spot_id, comment_id):
    if request.user.is_authenticated() and request.method == 'POST':
        Comment.objects.filter(id=comment_id).delete()
    return HttpResponseRedirect(reverse('spot_detail', args=(spot_id,)))


@login_required
def reply_comment(request, spot_id, comment_id):
    if request.user.is_authenticated() and request.method == 'POST':
        reply_text = request.POST.get('reply_text')
        if reply_text:
            comment = Comment.objects.get(id=comment_id)
            CommentReply.objects.create(
                text=reply_text, comment=comment, poster=request.user
            )

    return HttpResponseRedirect(reverse('spot_detail', args=(spot_id,)))


@login_required
def delete_reply(request, spot_id, reply_id):
    user = request.user
    if user.is_authenticated() and request.method == 'POST':
        reply = CommentReply.objects.get(id=reply_id)
        if user.id == reply.poster.id:
            reply.delete()
    return HttpResponseRedirect(reverse('spot_detail', args=(spot_id,)))


@login_required
def edit_comment(request, spot_id, comment_id):
    if request.user.is_authenticated() and request.method == 'POST':
        edit_type = request.POST['edit_type']
        _Model = Comment if edit_type == 'comment' else CommentReply
        comment_or_reply = _Model.objects.get(id=comment_id)
        comment_or_reply.text = request.POST['text']
        comment_or_reply.save()

    return HttpResponseRedirect(reverse('spot_detail', args=(spot_id,)))


@login_required

topspots/templates/topspots/confirmmodal.html
{% load static %}

<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h2 class="modal-title" id="confirmModalLabel">Are you sure you want to add:<br/>
                    <strong>{{ spot_name }}</strong>?
                </h2>
            </div>
            <div class="modal-body">
                <h4>
                    Once you add a spot, you will not be able to delete it.<br/>
                    Make sure the address and map image match the spot you want to add.
                </h4>
            </div>
            <div class="modal-footer">
                <script>
                    $(function () {
                        $('#btn-submit').click(function (e) {
                            $('#addSpotform').submit();
                            $('#confirmModal').modal('hide');
                        });
                    });
                </script>
                <button type="submit" id="btn-submit" class="btn btn-default">Really add</button>
                <button type="button" class="btn" data-dismiss="modal">Don't add yet</button>
            </div>
        </div>
    </div>
</div>

topspots/templates/topspots/detail.html
{% extends 'topspots/base.html' %}
{% load static %}
{% block title %}{{ spot.short_name }}{% endblock %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'topspots/css/weather-icons.min.css' %}" type="text/css">
{% endblock %}
{% block body %}
    {% include 'topspots/packlogmodal.html' %}
    <div align="center" class="jumbotron">
        <div class="row">
            <h1 class="fancy col-sm-offset-2 col-sm-8">
                {{ spot.short_name }}
                {% include 'topspots/favbutton.html' %}
                {% include 'topspots/nearbybutton.html' with spot_name=spot.name %}
            </h1>
            {% if user.is_authenticated %}
                <div class="col-sm-2">
                    <figure class="figure" type="button">
                        <a href="#">
                            <img src="{% static 'topspots/images/lipo2.png' %}" data-toggle="modal"
                                 data-target="#packLog" class="figure-img">
                        </a>
                        <figcaption class="figure-caption plain-light">Log packs</figcaption>
                    </figure>
                </div>
            {% endif %}
        </div>
        {% if spot.total_packs_flown > 0 %}
            <p>
                <span class="fancy">{{ spot.total_packs_flown }}</span> pack{{ spot.total_packs_flown|pluralize }} flown at this spot.
                {% if user.is_authenticated %}
                    <span class="fancy">{{ user_packs }}</span> by you.
                {% endif %}
            </p>
        {% endif %}
    </div>

    <div align="center">
        <p>
            {% if airports %}
                {% include 'topspots/airportmodal.html' %}
                <a href="#" data-toggle="modal" data-target="#airportInfo">
                    <i class="fa fa-plane text-warning fa-lg" aria-hidden="true"></i>
                    <i class="fa fa-warning text-warning fa-lg" aria-hidden="true"></i>
                </a>
            {% endif %}
        </p>


        <div class="btn-group" role="group">
            <button id="switch-rmap" type="button" class="btn btn-default active"><i class="fa fa-map-o fa-lg"></i></button>
            <button id="switch-satmap" type="button" class="btn btn-default"><i class="fa fa-globe fa-lg"></i></button>
        </div>

        <figure class="figure">
            <a href="{{ spot.google_maps_places_url }}" style="text-decoration: none">
                <img id="spot-map" src="{{ spot.map_url }}" class="figure-img img-fluid img-rounded img-responsive" alt="I'm the map.">
            </a>
            <figcaption class="figure-caption plain-light">Click map for directions and more details.</figcaption>
        </figure>
        <script>
            var $map = $('#spot-map');
            var $rMapSwitch = $('#switch-rmap')
            var $satMapSwitch = $('#switch-satmap')
            var url1 = '{{ spot.map_url|escapejs }}';
            var url2 = '{{ spot.sat_map_url|escapejs }}';
            $rMapSwitch.click(function (e) {
                $map.prop('src', url1);
                $rMapSwitch.addClass('active')
                $satMapSwitch.removeClass('active');
            });
            $satMapSwitch.click(function (e) {
                $map.prop('src', url2);
                $satMapSwitch.addClass('active')
                $rMapSwitch.removeClass('active');
            });

        </script>
        <hr>
        <!-- Weather conditions -->
        <div class="list-header">
            <h1 class="fancy">Conditions </h1>
            <h6 class="plain-light">(last checked at {{ weather_checked_at|date:"P" }}) <a href="http://forecast.io/">Powered by Forecast</a></h6>
        </div>
        <br/>
        <div class="row" align="center">
            <div class="col-sm-4">
                <i class="wi wi-strong-wind {% if wind >= 10 %}text-danger{% endif %}" style="font-size: 2em"></i>
                <h3>Wind Speed: {{ wind }} mph</h3>

            </div>

            <div class="col-sm-4">
                <i class="wi wi-rain {% if rain >= 50 %}text-danger{% endif %}" style="font-size: 2em"></i>
                <h3>Chance of Rain: {{ rain }}%</h3>
            </div>

            <div class="col-sm-4">
                <i class="wi wi-thermometer {% if temp >= 90 %}text-danger{% endif %}" style="font-size: 2em"></i>
                <h3>Temperature: {{ temp }}&deg;F</h3>
            </div>
        </div>
    </div>


    <hr>

    <!-- Comments -->
    {% if spot.comment_set.all or user.is_authenticated %}
    <div class="list-header" align="center">
        <h1 class="fancy">Comments</h1>
    </div>
    <br/>
    {% endif %}

    <!-- Comment box -->
    {% if user.is_authenticated %}
        <form class="form" method="post" action="{% url 'comment' spot.id %}">
            <div class="form-group">
                <div class="col-sm-4">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-comment"></i></span>
                        <input name="comment" placeholder="Tell people something about this spot"
                               class="form-control"  type="text">
                    </div>


                </div>
                <button type="submit" class="btn btn-default">Comment</button>
            </div>
            {% csrf_token %}
        </form><br/><br/>
    {% endif %}

    {% if spot.comment_set.all %}
        <div class="panel panel-default">
            {% for comment in spot.ordered_comments %}
                <div class="panel-heading row" id="comment-{{ comment.id }}">
                    <div class="col-sm-10">
                        <strong>{{ comment.poster.username }}</strong>
                        <em style="margin-left: 2em">{{ comment.created|date:'M d \'y \a\t H:i' }}</em>
                    </div>
                    <div class="btn-group col-sm-2" role="group">
                        {% if comment.poster == user %}

                            <form id="delete-comment-form-{{ comment.id }}" class="form"
                                  method="post" action="{% url 'delete_comment' spot.id comment.id %}">
                                {% csrf_token %}
                            </form>

                            {% include 'topspots/editmodal.html' with edit_type='comment' %}

                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-edit"></i> <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#" data-toggle="modal"
                                           data-target="#comment-{{ comment.id }} .editModal">Edit</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <a href="javascript:;"
                                           onclick="$('#delete-comment-form-{{ comment.id }}').submit();">Delete</a>
                                    </li>
                                </ul>
                            </div>

                        {% endif %}

                        {% if user.is_authenticated %}
                            {% include 'topspots/replymodal.html' %}
                            <button type="button" class="btn btn-default" data-toggle="modal"
                                    data-target="#comment-{{ comment.id }} .replyModal">
                                Reply
                            </button>
                        {% endif %}
                    </div>
                </div>

                <div class="panel-body">
                    <div class ="row">
                        <div class="col-sm-8">
                            {{ comment.text }}
                        </div>
                    </div>
                    <br/>

                    <!-- Comment replies -->
                    {% if comment.commentreply_set %}
                        {% for reply in comment.commentreply_set.all %}
                            <div class="row" style="padding-left: 1em" id="reply-{{ reply.id }}">
                                <div class="col-sm-8 well">
                                    <p>{{ reply.text }}</p>
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <p>
                                                <strong>{{ reply.poster.username }}</strong>
                                                <em style="margin-left: 2em">{{ reply.created|date:'M d \'y \a\t H:i' }}</em>
                                            </p>
                                        </div>
                                        {% if reply.poster == user %}
                                            {% include 'topspots/editmodal.html' with edit_type='reply' comment=reply %}
                                            <form id="delete-reply-form-{{ reply.id }}" class="form"
                                                  method="post" action="{% url 'delete_reply' spot.id reply.id %}">
                                                {% csrf_token %}
                                            </form>
                                            <div class="col-sm-2">
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-default dropdown-toggle"
                                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fa fa-edit"></i> <span class="caret"></span>
                                                    </button>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="#" data-toggle="modal"
                                                               data-target="#reply-{{ reply.id }} .editModal">Edit</a></li>
                                                        <li role="separator" class="divider"></li>
                                                        <li>
                                                            <a href="javascript:;"
                                                               onclick="$('#delete-reply-form-{{ reply.id }}').submit();">
                                                                Delete
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}

                </div>
            {% endfor %}
        </div>
    {% endif %} <!-- If comments -->

    <div class="list-header" align="center">
        <h1 class="fancy">Featured Video</h1>
    </div>
    <div align="center">
        <!-- Featured video here -->
        {{ spot.currently_featured_video.html|safe }}
        {% include 'topspots/featuresubmitmodal.html' %}
        <p><a href="#" data-toggle="modal" data-target="#featureSubmitModal">Want us to feature your video?</a></p>
    </div>

{% endblock %}

topspots/templates/topspots/nearbybutton.html
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
<a href="{% url 'spot_search' %}?search_query={{ spot_name }}&searchtype=nearby">
    <span class="glyphicon glyphicon-map-marker text-danger"
          style="font-size: 0.6em"
          data-toggle="tooltip" data-placement="top" title="Search spots near this location"></span>
</a>

topspots/templates/topspots/next.html
?next={% if 'next' not in request.get_full_path %}{{ request.get_full_path|urlencode }}{% else %}/{% endif %}

topspots/templates/topspots/popover.html
{% if not user.is_authenticated %}
    data-toggle="popover"
    data-placement="top"
    data-trigger="click"
    data-content="Want to contribute to the site? Please <a href='{% url "signup" %}?next={% if 'next' not in request.get_full_path %}{{ request.get_full_path|urlencode }}{% else %}/{% endif %}'>sign up</a> for an account or <a href='{% url "login" %}?next={% if 'next' not in request.get_full_path %}{{ request.get_full_path|urlencode }}{% else %}/{% endif %}'>log in</a> first."
{% endif %}